# Generated by Django 5.0 on 2026-04-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_long_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='image',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='filename',
            field=models.CharField(default='placeholder.png', help_text='Filename inside static/img/projects/ e.g. mygame1.png', max_length=200),
            preserve_default=False,
        ),
    ]
